# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wTbmY-csgdIKTKURHQ_HwDb1n6YX9Ay
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

original_img = cv2.imread('/content/Poinsettia.jpg')
original_img = cv2.cvtColor(original_img,cv2.COLOR_BGR2RGB)
plt.imshow(original_img)
plt.title('Original Image')

hsv_img = cv2.cvtColor(original_img , cv2.COLOR_RGB2HSV)
h,s,v = cv2.split(hsv_img)

green = (120,195,200)
red_low = (170, 255, 255)
red_high =(18, 255, 255)

#show the selected colors in RGB
from matplotlib.colors import hsv_to_rgb
green_sq = np.full((10, 10, 3),(0,225,120), dtype=np.uint8) / 255.0
red_low_sq = np.full((10, 10, 3), red_low, dtype=np.uint8) / 255.0
red_high_sq = np.full((10, 10, 3),red_high, dtype=np.uint8) / 255.0

plt.subplot(1, 3, 1)
plt.imshow(hsv_to_rgb(green_sq))
# plt.subplot(1, 3, 2)
# plt.imshow(hsv_to_rgb(red_low_sq))
# plt.subplot(1, 3, 3)
# plt.imshow(hsv_to_rgb(red_high_sq))

hsv_img = cv2.cvtColor(original_img , cv2.COLOR_RGB2HSV)
h,s,v=cv2.split(hsv_img)
# s[h>165] = 135
# v[h>165] = 120
h[h<25] += 50
h[h>165] -=110
hsv_img[:,:,0] = h.astype(int)
hsv_img[:,:,1] = s
hsv_img[:,:,2] = v
img = cv2.cvtColor(hsv_img , cv2.COLOR_HSV2RGB)
plt.rcParams['figure.figsize'] = (20,10)
plt.subplot(1,2,1)
plt.imshow(original_img)
plt.subplot(1,2,2)
plt.imshow(img)

import matplotlib.image as mpimg
mpimg.imsave('result-22.jpg',img)

"""توضیحات:ابتدا تصویر را به فضای اچ اس وی میبریم.سپس باتوجه به بازه ای رنگ قرمزو سبز مربوط به مولفه ی اچ،مقدار این مولفه را از حول مقادیر قرمز به حول مقادیر سیز شیفت میدهیم."""